---
title: "Papers and presentations"
---

# Publications

Oxbury, R., & de Leeuw, E. (2020). Style-shifting in Multicultural London English in an all-girls homework club. *English Today, 36*(3), 59--69. Authors' proofs [here](pdfs/english_today.pdf).

Oxbury, R. (2020). The forms and functions of “Breaking into song” during in-group conversations. *Text & Talk, 40*(2), 195--218. Author's proofs [here](pdfs/text_and_talk.pdf).

Oxbury, R., & McCarthy, K. (2019). Acquiring a multiethnolect: the production of diphthongs by children and adolescents in West London. In Proceedings of the 19th International Congress of Phonetic Sciences. To be presented at the International Congress of Phonetic Sciences, Melbourne, August 2019. Full paper [here](pdfs/390_OxburyMcCarthy_final.pdf).

# Conference presentations

Oxbury, R. (2018). Old contexts for new changes in Multicultural London English? Presentation given at Sociolinguistic Symposium 22, University of Auckland, 27th--30th June.

Oxbury, R. (2017). Functions of "break[ing] into song" in interactions between three sisters. Presentation given at iMean 5, University of West England, 6th--8th April. Slides [here](pdfs/iMean_final.pdf).

Oxbury, R. & de Leeuw, E. (April 2017). Situational style-shifting in Multicultural London English in an all girls homework club. Presentation given at Language Variation and Change Southern England, University of Suffolk, 12th April. Slides [here](pdfs/Oxbury_deLeeuw_LVCSE.pdf).